name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: 'UTF-8'

    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Configure git
        shell: pwsh
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "ok-oldking@users.noreply.github.com"
          git config --global user.name "ok-oldking"
          echo "action_state=yellow" >> $env:GITHUB_ENV
          Write-Host "Current state: $env:action_state"

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set UTF-8 encoding
        shell: cmd
        run: |
          set PYTHONIOENCODING=utf-8
          set PYTHONLEGACYWINDOWSSTDIO=utf-8
          echo PYTHONIOENCODING=utf-8 >> %GITHUB_ENV%

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: inline_ok_requirements
        run: |
          python -m ok.update.inline_ok_requirements --tag ${{ github.ref_name }}

      - name: Run tests
        shell: pwsh
        run: |
          Get-ChildItem -Path "tests/*.py" | ForEach-Object {
              Write-Host "Running tests in $($_.FullName)"
              python -m unittest $_.FullName
          }

      #      - name: Sync Repositories
      #        id: sync
      #        uses: ok-oldking/partial-sync-repo@master
      #        with:
      #          repos: |
      #            https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/Luo-Po/ok-wuthering-waves-echo
      #          sync_list: 'deploy.txt'
      #          tag: ${{ github.ref_name }}
      #          gitignore_file: '.update_repo_gitignore'
      #          show_author: true

      - name: Build with PyAppify Action
        id: build-app
        uses: ok-oldking/pyappify-action@master

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: false
          body: |
            ### 下载说明
            解压zip包后双击ok-boilerplate.exe运行，支持应用内更新
            
            ### 更新日志 ${{ steps.sync.outputs.start_tag }} -> ${{ steps.sync.outputs.end_tag }}
            ${{ steps.sync.outputs.changes_with_asterisk }}
          files: pyappify_dist/*